package com.bunizz.instapetts.constantes;

public interface BUNDLES {

    String DESCRIPCION = "DESCRIPCION";
    String PHOTO = "PHOTO";
    String PHOTO_TUMBH = "PHOTO_TUMBH";

    String PHOTO_LOCAL = "PHOTO_LOCAL";
    String PATH_SELECTED = "PATH_SELECTED";
    String URI_FOTO = "URI_FOTO";
    String NOTIFICATION_TIPE = "NOTIFICATION_TIPE";
    String POST_TYPE="POST_TYPE";
    String ID_POST ="ID_POST";
    String CAN_COMMENT ="CAN_COMMENT";


    String TITLE = "TITLE";
    String BODY = "BODY";
    String TYPE_NOTIFICACION = "TYPE_NOTIFICACION";
    String ID_USUARIO = "ID_USUARIO";
    String NAME_USUARIO = "NAME_USUARIO";
    String URL_RESOURCE = "URL_RESOURCE";


    String UUID = "UUID";

    // PET BUNDLES WIZZARD
    String TYPE_PET = "TYPE_PET";
    String RAZA_PET = "RAZA_PET";
    String RAZA_PET_ID = "RAZA_PET_ID";
    String EDAD_PET = "EDAD_PET";
    String GENERO_PET = "GENERO_PET";
    String NAME_PET = "NAME_PET";
    String ID_PET = "ID_PET";
    String URL_PHOTO_PET = "URL_PHOTO_PET";
    String DESCRIPCION_PET = "DESCRIPCION_PET";
    String PESO_PET = "PESO_PET";


    String IS_ME ="IS_ME";

    String PETBEAN ="PETBEAN";

    String VIDEO_DURATION ="VIDEO_DURATION";
    String VIDEO_ASPECT ="VIDEO_ASPECT";


    String DOWNLOADS_INFO ="DOWNLOADS_INFO";

    String TIPO_DESCARGA ="TIPO_DESCARGA";

    String PET_REQUEST ="PET_REQUEST";


    //postbean

    String POST_IS_LIKED ="POST_IS_LIKED";
    String POST_ID_POST="POST_ID_POST";
    String POST_THUMBH_VIDEO="POST_THUMBH_VIDEO";
    String POST_ID_USUARIO="POST_ID_USUARIO";
    String POST_UUID="POST_UUID";
    String POST_IS_SAVED="POST_IS_SAVED";
    String POST_IS_CENSORED="POST_IS_CENSORED";
    String POST_DESCRIPCION="POST_DESCRIPCION";
    String POST_LIKES="POST_LIKES";
    String POST_URLS="POST_URLS";
    String POST_NAME="POST_NAME";
    String POST_ASPECT="POST_ASPECT";
    String POST_FOTO_USER="POST_FOTO_USER";

}
