package com.bunizz.instapetts.constantes;

public interface PREFERENCES {
    String IS_LOGUEDD = "IS_LOGEDD";
    String IS_INTRO_COMPLETED = "IS_INTRO_COMPLETED";
    String FOTO_PROFILE_USER = "FOTO_PROFILE_USER";
    String FOTO_PROFILE_USER_THUMBH = "FOTO_PROFILE_USER_THUMBH";
    String IS_NEW_USER = "IS_NEW_USER";
    String UUID = "UUID";
    String TOKEN = "TOKEN";
    String LAT ="LAT";
    String LON = "LON";
    String DESCRIPCCION = "DESCRIPCCION";
    String FROM_PICKER ="FROM_PICKER";
    String NAME_USER ="NAME_USER";
    String IS_FIRST_USER ="IS_FIRST_USER";
    String ID_USER_FROM_WEB ="ID_USER_FROM_WEB";
    String ANDROID_ID ="ANDROID_ID";
    String CP ="CP";
    String NAME_PRE_USER="NAME_PRE_USER";
    String NAME_TAG_INSTAPETTS ="NAME_TAG_INSTAPETTS";
    String URI_TEMP_SMOOT ="URI_TEMP_SMOOT";
    String CURRENTS_FRIENDS = "CURRENTS_FRIENDS";
    String IDIOMA="IDIOMA";
    String ESTATUS_SUBIDA_VIDEO ="ESTATUS_SUBIDA_VIDEO";
    String PORCENTAJE_SUBIDA ="PORCENTAJE_SUBIDA";

    String LOCATION_CHANGED ="LOCATION_CHANGED";

    //NOTIFICATIONS PUSH

    String PUSH_ME_GUSTAS = "PUSH_ME_GUSTAS";
    String PUSH_SEGUIDORES ="PUSH_SEGUIDORES";
    String PUSH_MASCOTAS_LIKE ="PUSH_MASCOTAS_LIKE";
    String PUSH_CONTENIDO_SEGUIDOS ="PUSH_CONTENIDO_SEGUIDOS";
    String PUSH_TIPS_NOTICIAS ="PUSH_TIPS_NOTICIAS";


    String ALLOW_LOCATION_POST ="ALLOW_LOCATION_POST";
    String ADDRESS_USER = "ADDRESS_USER";

    String FECHA_BACKUP_FILE="FECHA_BACKUP_FILE";

    String ADS_ACTIVADOS ="ADS_ACTIVADOS";


    String OPEN_POST_ADVANCED_FROM ="OPEN_POST_ADVANCED_FROM";

    String MODO_INVITADO ="MODO_INVITADO";

    String PRIMER_USUARIO_INVITADO ="PRIMER_USUARIO_INVITADO";

    String DATE_OF_USE ="DATE_OF_USE";
    String COUNTER_OPEN_APP ="COUNTER_OPEN_APP";
    String RATE_APP="RATE_APP";

}
